Initial implementation of classes.
TonyLiu836/GetFit pull request #14
Opened 2023-11-02 03:27 UTC by TonyLiu836

Initial implementation of some basic functionality.

2023-11-02 04:20 UTC, RunpengNie commented
Remember to include the Issue number in the PR's description.

2023-11-05 07:49 UTC, RunpengNie commented
Overall, it is a good design and implementation.

2023-11-05 09:26 UTC, RunpengNie requested changes

2023-11-05 09:26 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/User.java
> +    String name;
Make `name` public, and all the other attributes should be private.

2023-11-05 22:27 UTC, RunpengNie commented
The other minor change: change the branch name to `7-Design-Program-Logic-2`. Make sure the only special character we have in branch names is `-`.

2023-11-05 22:29 UTC, RunpengNie approved these changes
LGTM! Now we need one more review from Joe @Junzhou-712  or Vincent @VincentXiao997 .

2023-11-11 20:45 UTC, Junzhou-712 approved these changes
LGTM! Thanks

2023-11-12 17:15 UTC, merged