7.3 design program logic
TonyLiu836/GetFit pull request #16
Opened 2023-11-13 03:41 UTC by Junzhou-712

Implemented IExerciseEvent and some derived classes. @TonyLiu836 @RunpengNie @VincentXiao997 Could you help me to review this part. Thanks!
And I am curious that whether the flexibility class and customized class need an unit or not.

2023-11-14 05:02 UTC, RunpengNie commented
The first thing that needs attention to is that no branch will be merged with the main branch except for release.

2023-11-14 05:06 UTC, RunpengNie commented
Remember to request review on your PR page.

2023-11-14 05:14 UTC, RunpengNie commented
The other minor change: we should name the branch name `7-Design-Program-Logic-3`. Make sure the only special character we have in branch names is -.

Tony's PR also had this problem. Remember to follow the branch naming convention next time.

2023-11-14 06:16 UTC, RunpengNie requested changes

2023-11-14 06:16 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Cardio.java
> +       return "0";
This method always returns "0", which seems inconsistent with the other classes where `getAdditionalNotes` and `setAdditionalNotes` are implemented. You may want to reconsider this function for `Cardio`.

2023-11-14 06:16 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Flexibility.java
> +        return Duration.ZERO;
I don't think this design is reasonable. As we discussed on the issue page, all sport classes implement the IExerciseEvent interface, which means that for these classes they should implement all the properties of the interface with practical meaning.

2023-11-14 06:16 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Flexibility.java
> +        return "0";
Same here.

2023-11-14 06:16 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Strength.java
> +        return "0";
Same here.

2023-11-14 06:17 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Strength.java
> +      return "Exercise name: " + name + ", Weight: " + weight + weightUnit.toString() + ", Reps: " + reps;
Nice design here, we should make our `Unit` classes support `toString()` comment @TonyLiu836 .

2023-11-24 04:41 UTC, Junzhou-712 commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Flexibility.java
> +        return Duration.ZERO;
I am still confused with the specific type for flexibility, especially for the duration, what is the practical mean from a flexibility exercises, and which unit should we use for following build?

2023-11-24 22:25 UTC, Junzhou-712 commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Flexibility.java
> +        return Duration.ZERO;
Fixed

2023-11-25 01:23 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Strength.java
> +      return "Exercise name: " + name + ", Weight: " + weight + weightUnit.toString() + ", Reps: " + reps;
Hey @TonyLiu836  plz reply here if you noticed this request, then I will resolve this comment since this is not a problem of Joe's code.

2023-11-26 22:45 UTC, TonyLiu836 commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Strength.java
> +      return "Exercise name: " + name + ", Weight: " + weight + weightUnit.toString() + ", Reps: " + reps;
What do you mean by "this is not a problem of Joe's code"? Should I add the toString() method to the `Unit` classes or not?

2023-11-26 23:40 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Strength.java
> +      return "Exercise name: " + name + ", Weight: " + weight + weightUnit.toString() + ", Reps: " + reps;
Yes. This is just a tiny little minor change and you can just add it in your next PR.

2023-12-02 02:50 UTC, Junzhou-712 commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Strength.java
> +        return "0";
Resolved.

2023-12-02 02:50 UTC, Junzhou-712 commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Cardio.java
> +       return "0";
Resolved.

2023-12-02 02:51 UTC, Junzhou-712 commented
@RunpengNie @TonyLiu836 @VincentXiao997 Could you review this feature about those classes? Thanks!

2023-12-02 04:25 UTC, RunpengNie requested changes
I believe your code is clear enough for anyone to understand without any problem. All comments are unnecessary and can be deleted.

2023-12-02 04:25 UTC, RunpengNie commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Flexibility.java
> +    public Flexibility(String name) {
The constructor should include `duration`.

2023-12-04 02:22 UTC, Junzhou-712 commented on GetFit/src/main/java/com/TheTroisMousquetaires/GetFit/entity/Flexibility.java
> +    public Flexibility(String name) {
Done.

2023-12-04 02:28 UTC, RunpengNie approved these changes
Nice work! LGTM.

2024-01-27 18:07 UTC, TonyLiu836 approved these changes
Good stuff :+1:

2024-02-04 06:47 UTC, merged